package com.andrew.ens.user_status.domain;

public enum Status {
    TEMPLATE_CREATE_NAME_WAITING,
    TEMPLATE_CREATE_TEXT_WAITING,
    TEMPLATE_CREATE_CONTACT_NAME_WAITING,
    TEMPLATE_CREATE_CONTACT_EMAIL_WAITING,
    TEMPLATE_CREATE_CONTACT_PHONE_NUMBER_WAITING,
    TEMPLATE_CREATE_CONTACT_WAITING
}
