package com.andrew.ens;

public enum Status {
    TEMPLATE_CREATE_NAME_WAITING,
    TEMPLATE_CREATE_TEXT_WAITING,
    TEMPLATE_CREATE_CONTACT_NAME_WAITING,
    TEMPLATE_CREATE_CONTACT_EMAIL_WAITING,
    TEMPLATE_CREATE_CONTACT_PHONE_NUMBER_WAITING,
    TEMPLATE_CREATE_CONTACT_WAITING,
    MAIN_MENU_WAITING,
    SETTINGS_WAITING,
    SETTINGS_CHOOSE_TEMPLATE_WAITING,
    SETTINGS_DELETE_TEMPLATE_WAITING,
    SETTINGS_EDIT_TEMPLATE_WAITING,
    SETTINGS_BACK_TO_MENU_WAITING,
    EDIT_TEMPLATES_WAITING,
    EDIT_TEMPLATES_ADD_CONTACT_CHOSE_TEMPLATE_WAITING,
    EDIT_TEMPLATES_ADD_CONTACT_CREATE_CONTACT,
    EDIT_TEMPLATES_DELETE_CONTACT_WAITING,
    EDIT_TEMPLATES_DELETE_CONTACT_CHOSE_TEMPLATE_WAITING,
    EDIT_TEMPLATES_DELETE_CONTACT_CHOSE_CONTACT_WAITING,
    EDIT_TEMPLATES_ADD_CONTACT_CREATE_CONTACT_NAME_WAITING,
    EDIT_TEMPLATES_ADD_CONTACT_CREATE_CONTACT_EMAIL_WAITING,
    EDIT_TEMPLATES_ADD_CONTACT_CREATE_CONTACT_PHONE_NUMBER_WAITING,
    EDIT_TEMPLATES_CHANGE_THE_TEMPLATE_NAME_WAITING,
    EDIT_TEMPLATES_CHANGE_THE_TEMPLATE_NAME_CHOSE_TEMPLATE_WAITING,
    EDIT_TEMPLATES_CHANGE_THE_TEMPLATE_NAME_CHOSE_TEMPLATE_NEW_NAME_WAITING
}
