package com.andrew.ens;

public enum Status {
    CREATE_TEMPLATE_NAME_WAITING,
    CREATE_TEMPLATE_TEXT_WAITING,
    MAIN_MENU_WAITING,
    MAIN_MENU_SEND_EMERGENCY_MESSAGE_WAITING,
    SETTINGS_WAITING,
    SETTINGS_CHOOSE_TEMPLATE_WAITING,
    SETTINGS_DELETE_TEMPLATE_WAITING,
    SETTINGS_DELETE_TEMPLATE_CONFIRM_WAITING,
    SETTINGS_EDIT_TEMPLATE_CHOSE_TEMPLATE_WAITING,
    EDIT_TEMPLATES_WAITING,
    EDIT_TEMPLATES_DELETE_CONTACT_CHOSE_TEMPLATE_WAITING,
    EDIT_TEMPLATES_DELETE_CONTACT_CHOSE_TEMPLATE_CONFIRM_WAITING,
    EDIT_TEMPLATES_DELETE_ALL_CONTACTS_CONFIRM,
    EDIT_TEMPLATES_ADD_CONTACT_CREATE_CONTACT_NAME_WAITING,
    EDIT_TEMPLATES_ADD_CONTACT_CREATE_CONTACT_EMAIL_WAITING,
    EDIT_TEMPLATES_ADD_CONTACT_CREATE_CONTACT_PHONE_NUMBER_WAITING,
    EDIT_TEMPLATES_CHANGE_THE_TEMPLATE_NAME_WAITING,
}
